config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'
  devise_for :users
  get 'brands/index'
  get 'functions/index'
  get 'tastes/index'
  get 'prices/index'
  get 'roll_screens/index'
  get 'roman_shades/index'
  get 'laces/index'
  get 'drapes/index'
  resources :wallpapers do
    collection { post :import }
  end
  resources :wallpapers do
    collection do
      delete 'destroy_all'
    end
  end
  resources :drapes do
    collection { post :import }
  end
  resources :drapes do
    collection do
      delete 'destroy_all'
    end
  end
  resources :laces do
    collection { post :import }
  end
  resources :laces do
    collection do
      delete 'destroy_all'
    end
  end
  resources :roman_shades do
    collection { post :import }
  end
  resources :roman_shades do
    collection do
      delete 'destroy_all'
    end
  end
  resources :roll_screens do
    collection { post :import }
  end
  resources :roll_screens do
    collection do
      delete 'destroy_all'
    end
  end
  resources :brands do
    collection { post :import }
  end
  resources :brands do
    collection do
      delete 'destroy_all'
    end
  end
  resources :functions do
    collection { post :import }
  end
  resources :functions do
    collection do
      delete 'destroy_all'
    end
  end
  resources :prices do
    collection { post :import }
  end
  resources :prices do
    collection do
      delete 'destroy_all'
    end
  end
  resources :tastes do
    collection { post :import }
  end
  resources :tastes do
    collection do
      delete 'destroy_all'
    end
  end

  def after_sign_in_path_for(resource)
    home_index_path
  end
  # ログアウト後の遷移先
  def after_sign_out_path_for(resource)
    new_user_session_path
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      brand = find_by(name: row["name"]) || new
      # CSVからデータを取得し、設定する
      brand.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      brand.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "disp_name"]
  end
end

app/models/drape.rb
class Drape < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      drape = find_by(code: row["code"]) || new
      # CSVからデータを取得し、設定する
      drape.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      drape.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["id", "code", "functions", "price", "brand", "taste"]
  end
end

app/models/function.rb
class Function < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      function = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      function.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      function.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "disp_name", "func_description", "selectables"]
  end
end

app/models/lace.rb
class Lace < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      lace = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      lace.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      lace.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["code", "functions", "price", "brand"]
  end
end

app/models/price.rb
class Price < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      price = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      price.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      price.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["section", "disp_value"]
  end
end

app/models/roll_screen.rb
class RollScreen < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      roll_screen = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      roll_screen.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      roll_screen.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["code", "functions", "price"]
  end
end

app/models/roman_shade.rb
class RomanShade < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      roman_shade = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      roman_shade.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      roman_shade.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["code", "functions", "price", "brand", "taste"]
  end
end

app/models/taste.rb
class Taste < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      taste = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      taste.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      taste.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "disp_name", "image", "image2", "image3"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable
  # devise :database_authenticatable,
  #        :registerable,
  #        :confirmable,
  #        :recoverable,
  #        :rememberable,
  #        :trackable,
  #        :validatable
end

app/models/wallpaper.rb
class Wallpaper < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      wallpaper = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      wallpaper.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      wallpaper.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["code"]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/tastes_controller.rb
class TastesController < ApplicationController
  def index
    @tastes = Taste.all
  end
  def destroy
    Taste.destroy_all
    redirect_to tastes_path
  end
  def import
    Taste.import(params[:file])
    redirect_to tastes_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/drapes_helper.rb
module DrapesHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/laces_helper.rb
module LacesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/roll_screens_helper.rb
module RollScreensHelper
end

app/helpers/tastes_helper.rb
module TastesHelper
end

app/helpers/wallpapers_helper.rb
module WallpapersHelper
end

app/views/tastes/index.html.erb
<div class="container">
  <%= form_tag import_tastes_path, multipart: true do %>
    <div class="row border border-dark py-3">
      <div class="col-6 w-100"> 
        <%= file_field_tag :file , id: 'elmFile', onchange: 'selectFile()',class:"w-100"%>
      </div>
      <div class="col-6 w-100">
        <%= submit_tag "Import", class:"w-100 bg-info", id: 'btnImport', disabled: true  %>
      </div>
    </div>
  <% end %>
  <div class="row border border-dark py-3">
    <div class="col-6 w-100">
      <%= @tastes.count %>items
    </div>
    <div class="col-6 w-100">
    <% if @tastes.count > 0 %>
      <%= button_to "全て削除", destroy_all_tastes_path, method: :delete, data: { confirm: "削除してよろしいですか？", commit: "削除する", cancel: "やめる" },class:"w-100 bg-danger text-white" %>
    <% end %>
    </div>
  </div>
</div>
<div class="container bg-secondary">
  <div class="row w-100 my-3">
    <div class="col-12 w-100 text-white">
      Price_SQL_CODE
    </div>
  </div>
</div>
<div class="container mb-5" style="font-size:9px">
  <div class="row">
    <% if @tastes.count > 0 %>
      <div class="col-12">truncate table tastes;</div>
    <% end %>
  </div>
  <div class="row">
    <% @tastes.each do |taste| %>
      <div class="col-12">
      insert into koike_sim_db.tastes(name,disp_value,image,image2,image3,`createdAt`,`updatedAt`) values (
      <% if taste.name.present? %>"<%= taste.name %>",<% else %>null,<% end %>
      <% if taste.disp_name.present? %>"<%= taste.disp_name %>",<%else%>null,<% end %>
      <% if taste.image.present? %>"<%= taste.image %>",<% else %>null,<% end %>
      <% if taste.image2.present? %>"<%= taste.image2 %>",<% else %>null,<% end %>
      <% if taste.image3.present? %>"<%= taste.image3 %>",<% else %>null,<% end %>
      now(),now());
      </div>
    <% end %>
  </div>
</div>

<script>
  function selectFile() {
    if (document.getElementById("elmFile").value === ""){
        document.getElementById("btnImport").disabled = true;
    }
    else {
        document.getElementById("btnImport").disabled = false;
    }
}
</script>