config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'
  devise_for :users
  get 'brands/index'
  get 'functions/index'
  get 'tastes/index'
  get 'prices/index'
  get 'roll_screens/index'
  get 'roman_shades/index'
  get 'laces/index'
  get 'drapes/index'
  resources :wallpapers do
    collection { post :import }
  end
  resources :wallpapers do
    collection do
      delete 'destroy_all'
    end
  end
  resources :drapes do
    collection { post :import }
  end
  resources :drapes do
    collection do
      delete 'destroy_all'
    end
  end
  resources :laces do
    collection { post :import }
  end
  resources :laces do
    collection do
      delete 'destroy_all'
    end
  end
  resources :roman_shades do
    collection { post :import }
  end
  resources :roman_shades do
    collection do
      delete 'destroy_all'
    end
  end
  resources :roll_screens do
    collection { post :import }
  end
  resources :roll_screens do
    collection do
      delete 'destroy_all'
    end
  end
  resources :brands do
    collection { post :import }
  end
  resources :brands do
    collection do
      delete 'destroy_all'
    end
  end
  resources :functions do
    collection { post :import }
  end
  resources :functions do
    collection do
      delete 'destroy_all'
    end
  end
  resources :prices do
    collection { post :import }
  end
  resources :prices do
    collection do
      delete 'destroy_all'
    end
  end
  resources :tastes do
    collection { post :import }
  end
  resources :tastes do
    collection do
      delete 'destroy_all'
    end
  end

  def after_sign_in_path_for(resource)
    home_index_path
  end
  # ログアウト後の遷移先
  def after_sign_out_path_for(resource)
    new_user_session_path
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      brand = find_by(name: row["name"]) || new
      # CSVからデータを取得し、設定する
      brand.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      brand.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "disp_name"]
  end
end

app/models/drape.rb
class Drape < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      drape = find_by(code: row["code"]) || new
      # CSVからデータを取得し、設定する
      drape.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      drape.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["id", "code", "functions", "price", "brand", "taste"]
  end
end

app/models/function.rb
class Function < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      function = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      function.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      function.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "disp_name", "func_description", "selectables"]
  end
end

app/models/lace.rb
class Lace < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      lace = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      lace.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      lace.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["code", "functions", "price", "brand"]
  end
end

app/models/price.rb
class Price < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      price = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      price.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      price.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["section", "disp_value"]
  end
end

app/models/roll_screen.rb
class RollScreen < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      roll_screen = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      roll_screen.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      roll_screen.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["code", "functions", "price"]
  end
end

app/models/roman_shade.rb
class RomanShade < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      roman_shade = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      roman_shade.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      roman_shade.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["code", "functions", "price", "brand", "taste"]
  end
end

app/models/taste.rb
class Taste < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      taste = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      taste.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      taste.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "disp_name", "image", "image2", "image3"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable
  # devise :database_authenticatable,
  #        :registerable,
  #        :confirmable,
  #        :recoverable,
  #        :rememberable,
  #        :trackable,
  #        :validatable
end

app/models/wallpaper.rb
class Wallpaper < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      wallpaper = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      wallpaper.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      wallpaper.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["code"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/drapes_helper.rb
module DrapesHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/laces_helper.rb
module LacesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/tastes_helper.rb
module TastesHelper
end

app/helpers/wallpapers_helper.rb
module WallpapersHelper
end

app/views/layouts/_head.html.erb
<div class="row justify-content-center bg-dark sticky-top">
  <div class="col-12 text-center py-1 text-white">
    <%= link_to "SQL_Service", root_path,class:'col-12 w-100 text-white' %>
  </div>
</div>
<% if user_signed_in? %>
<div class="container">
  <div class="row">
    <%= link_to 'LOGOUT', destroy_user_session_path, method: :delete,class:"text-right col-12" %>
  </div>
</div>
<% end %>
<div class="row justify-content-around border border-dark bg-light py-2">
  <%= link_to "Drapes", drapes_path,class:'col-2 w-100 text-secondary text-center' %>
  <%= link_to "Laces", laces_path,class:'col-2 w-100 text-secondary text-center' %>
  <%= link_to "RomanShades", roman_shades_path,class:'col-2 w-100 text-secondary text-center' %>
  <%= link_to "RollScreens", roll_screens_path,class:'col-2 w-100 text-secondary text-center' %>
  <%= link_to "Wallpapers", wallpapers_path,class:'col-2 w-100 text-secondary text-center' %>
</div>
<div class="row justify-content-around border border-dark bg-light py-2">
  <%= link_to "Brands", brands_path,class:'col-3 w-100 text-secondary text-center' %>
  <%= link_to "Functions", functions_path,class:'col-3 w-100 text-secondary text-center' %>
  <%= link_to "Prices", prices_path,class:'col-3 w-100 text-secondary text-center' %>
  <%= link_to "Tastes", tastes_path,class:'col-3 w-100 text-secondary text-center' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MS2Import</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/head'%>
    <%= yield %>
  </body>
</html>